### Login user - SUCCESS CASE (assuming 'testuser1' with 'password123' exists)
POST http://127.0.0.1:5001/api/login
Content-Type: application/json

{
    "username": "testuser1",
    "password": "password123"
}

### Login user - FAIL CASE (Wrong Password)
POST http://127.0.0.1:5001/api/login
Content-Type: application/json

{
    "username": "testuser1",
    "password": "wrongpassword"
}

### Login user - FAIL CASE (User does not exist)
POST http://127.0.0.1:5001/api/login
Content-Type: application/json

{
    "username": "nonexistentuser",
    "password": "password123"
}